name: Update README with Recent Commits

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Update README with recent commits
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://github.com/NEO1717/readme-auto-updater/commits/main.atom"
          comment_tag_name: "LATEST_COMMITS"
          readme_path: "./README.md"
          commit_message: "chore: Update README with recent commits"
          max_post_count: 5
